name: yarn-install-with-cache
inputs:
  update-cache:
    description: Update the cache, only do this if you are update-node-modules-cache.yml
    default: "false"
description: Only update node_modules if on main
runs:
  using: composite
  steps:
    - name: Load node_modules from cache
      # Restore for all branches, but save for 'main'.
      uses: actions/cache/restore@v4
      with:
        path: node_modules/
        key: node-modules-${{ hashFiles('package.json') }}
    - name: Install dependencies
      shell: bash
      run: yarn install --non-interactive
    - name: Save node_modules to the cache
      if: github.ref == 'refs/heads/main' && inputs.update-cache == 'true'
      uses: actions/cache/save@v4
      with:
        path: node_modules/
        # We're assuming that variations on branches will slightly vary from main,
        # so it's always important to run yarn install --non-interactive after this
        # cache is restored.
        key: node-modules-v1-${{ hashFiles('package.json') }}
        enableCrossOsArchive: true
